#!/venvs/promptmap/bin/python3

import sys
import subprocess
import os


def main():
    """CLI wrapper for running Promptmap."""

    # Run from the project directory
    os.chdir("/venvs/promptmap/source/promptmap")

    # Construct the base command
    cmd = [sys.executable, "promptmap2.py"]

    # Append all user-provided CLI arguments
    cmd.extend(sys.argv[1:])

    # Execute the command
    subprocess.run(cmd)


if __name__ == "__main__":
    main()
